/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ALPHABETS: typeof import('./lib/constants').ALPHABETS
  const App: typeof import("./App").default
  const BreakpointContext: typeof import('./hooks/use-breakpoint').BreakpointContext
  const cn: typeof import('./lib/utils').cn
  const routeTree: typeof import("./routeTree.gen").routeTree
  const useBreakpoint: typeof import('./hooks/use-breakpoint').useBreakpoint
  const useSmoothScroll: typeof import('./hooks/use-smooth-scroll').useSmoothScroll
}
